name: Automatic Build

on: [push]

env:
  SOLUTION_FILE_PATH: MWSE.sln
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build LuaJIT
      working-directory: ${{env.GITHUB_WORKSPACE}}/deps/LuaJIT/src/
      run: msvcbuild.bat

    - name: Build MWSE
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Package
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd c:\projects\mwse
        mkdir build\dist
        xcopy misc\package build\dist /s /e /Y
        copy build\release\mwse.dll build\dist /Y
        copy deps\LuaJIT\src\lua51.dll build\dist /Y
        copy MWSE-Update\bin\Release\MWSE-Update.exe build\dist /Y
        copy MWSE-Update\bin\Release\Newtonsoft.Json.dll build\dist /Y
        copy MWSE-Update\bin\Release\Newtonsoft.Json.xml build\dist /Y
        cd build\dist
        7z a mwse.zip
        cd ..\release
        7z a mwse_debug_symbols.7z MWSE.pdb

    - name: Publish
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
            ${{env.GITHUB_WORKSPACE}}/build/dist/MWSE.zip
